#!/bin/sh
# postinst script for perfsonar-logstash-output-plugin

chown -R logstash:logstash /usr/lib/perfsonar/logstash/plugin/

PLUGIN_INSTALLED=$(/usr/share/logstash/bin/logstash-plugin list --verbose | grep logstash-output-opensearch)
#TODO: compare plugin installed version with package version
if [ ! -z "$PLUGIN_INSTALLED" ]; then
    #if upgrade, safely remove old plugin before adding new
    systemctl stop logstash
    /usr/share/logstash/bin/logstash-plugin remove $PLUGIN_INSTALLED
    /usr/share/logstash/bin/logstash-plugin install file:/usr/lib/perfsonar/logstash/plugin/logstash-output-plugin-offline-8.10.4.zip
    systemctl start logstash
else
    /usr/share/logstash/bin/logstash-plugin install file:/usr/lib/perfsonar/logstash/plugin/logstash-output-plugin-offline-8.10.4.zip
fi

#DEBHELPER#
exit 0
