#!/bin/sh
# postinst script for perfsonar-logstash-output-plugin

chown -R logstash:logstash /etc/perfsonar/logstash_output

PLUGIN_INSTALLED=$(/usr/share/logstash/bin/logstash-plugin list --verbose | grep logstash-output-opensearch)
#TODO: compare plugin installed version with package version
if [ ! -z "$PLUGIN_INSTALLED" ]; then
    #if upgrade, safely remove old plugin before adding new
    systemctl stop logstash
    /usr/share/logstash/bin/logstash-plugin remove $PLUGIN_INSTALLED
    /usr/share/logstash/bin/logstash-plugin install /usr/lib/perfsonar/logstash/plugin/logstash-output-opensearch.gem
    systemctl start logstash
else
    /usr/share/logstash/bin/logstash-plugin install /usr/lib/perfsonar/logstash/plugin/logstash-output-opensearch.gem
fi

#DEBHELPER#
exit 0
