FROM opensearchproject/logstash-oss-with-opensearch-output-plugin:8.9.0

#Copy files
COPY ./prometheus_pipeline/* /usr/lib/perfsonar/logstash/prometheus_pipeline/
COPY ./pipeline_etc/ /etc/perfsonar/logstash
COPY ./ruby/ /usr/lib/perfsonar/logstash/ruby
COPY ./scripts/ /usr/lib/perfsonar/logstash/scripts
COPY ./java/ /usr/lib/perfsonar/logstash/java

#Install caching library
USER root
RUN apt-get update -y && apt-get install -y maven python3 python3-yaml
RUN cd /usr/lib/perfsonar/logstash/java &&\
    mkdir maven &&\
    mvn -Dmaven.repo.local=/usr/lib/perfsonar/logstash/java/maven dependency:resolve &&\
    chown -R logstash:root /usr/lib/perfsonar/logstash/java/maven

#make config look like non-docker so scripts work
RUN  mkdir /etc/logstash &&\
       echo "" > /usr/share/logstash/config/pipelines.yml &&\
       ln -s /usr/share/logstash/config/pipelines.yml /etc/logstash/pipelines.yml
USER logstash

#Generate pipelines.yml
RUN python3 /usr/lib/perfsonar/logstash/scripts/enable_prometheus_pipeline.py
