#!/bin/sh
# postinst script for perfsonar-logstash-output-plugin

chown -R logstash:logstash /etc/perfsonar/logstash_output

LIST_OUTPUT=$(/usr/share/logstash/bin/logstash-plugin list --verbose logstash-output-opensearch)
CURRENT=${LIST_OUTPUT#*logstash/jdk}
PLUGIN='logstash-output-opensearch'
if [[ "$CURRENT" == *"$PLUGIN"* ]]; then
    #VERSION=${CURRENT#*$PLUGIN}
    # STOP LOGSTASH
    systemctl stop logstash
    /usr/share/logstash/bin/logstash-plugin remove $PLUGIN
    /usr/share/logstash/bin/logstash-plugin install /etc/perfsonar/logstash_output/logstash-output-opensearch.gem
    systemctl start logstash
else
    /usr/share/logstash/bin/logstash-plugin install /etc/perfsonar/logstash_output/logstash-output-opensearch.gem
fi

#DEBHELPER#
exit 0
